"""Pipeline data models: EventConfig, PipelineRun, PatientTask, Evidence.

Data flow:
  EventConfig ──→ PipelineRun ──→ PatientTask ──→ Evidence
                                       │              │
                                       └──→ Annotation ┘

State machines:
  PipelineRun:  QUEUED → RUNNING → COMPLETED | FAILED | CANCELLED
  PatientTask:  QUEUED → PROCESSING → COMPLETED | FAILED | NO_MATCH
                FAILED → QUEUED (retry)
                PROCESSING → QUEUED (stalled retry)
"""

import enum
from datetime import UTC, datetime
from uuid import uuid4

from sqlalchemy import Column, DateTime, Index, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.types import JSON
from sqlmodel import Field, SQLModel


# ── Enums ────────────────────────────────────────────────────────


class PipelineRunStatus(str, enum.Enum):
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class PipelineRunType(str, enum.Enum):
    SAMPLE = "sample"
    FULL = "full"


class PatientTaskStatus(str, enum.Enum):
    QUEUED = "queued"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    NO_MATCH = "no_match"


# Valid state transitions for PatientTask
_PATIENT_TASK_TRANSITIONS: dict[PatientTaskStatus, set[PatientTaskStatus]] = {
    PatientTaskStatus.QUEUED: {PatientTaskStatus.PROCESSING},
    PatientTaskStatus.PROCESSING: {
        PatientTaskStatus.COMPLETED,
        PatientTaskStatus.FAILED,
        PatientTaskStatus.NO_MATCH,
        PatientTaskStatus.QUEUED,  # stalled retry
    },
    PatientTaskStatus.FAILED: {PatientTaskStatus.QUEUED},  # retry
    PatientTaskStatus.COMPLETED: set(),
    PatientTaskStatus.NO_MATCH: set(),
}


# ── Models ───────────────────────────────────────────────────────


class EventConfig(SQLModel, table=True):
    """Configuration for a clinical event detection pipeline.

    Combines event semantics (what to detect) with LLM config (how to detect).
    Immutable once committed (is_committed=True).
    """

    __tablename__ = "event_configs"

    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    project_id: str = Field(foreign_key="projects.id", index=True)

    # Event definition
    name: str = Field(max_length=200)
    description: str = Field(sa_column=Column(Text, nullable=False))
    include_criteria: str = Field(sa_column=Column(Text, nullable=False))
    exclude_criteria: str = Field(sa_column=Column(Text, nullable=False, server_default=""))

    # Search patterns (generated by LLM or manually configured)
    search_patterns: dict = Field(default_factory=dict, sa_column=Column(JSON, nullable=False, server_default="{}"))

    # LLM configuration
    llm_provider: str = Field(max_length=50)
    llm_model: str = Field(max_length=200)
    llm_api_base: str | None = Field(default=None, max_length=500)
    llm_api_key: str | None = Field(default=None, max_length=500)

    # Calibration
    confidence_threshold: float | None = Field(default=None)
    is_committed: bool = Field(default=False)

    # Timestamps
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True),
    )


class PipelineRun(SQLModel, table=True):
    """A single execution of a pipeline (sample or full)."""

    __tablename__ = "pipeline_runs"

    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    project_id: str = Field(foreign_key="projects.id", index=True)
    event_config_id: str = Field(foreign_key="event_configs.id", index=True)

    run_type: str = Field(max_length=20)  # "sample" or "full"
    status: PipelineRunStatus = Field(default=PipelineRunStatus.QUEUED)

    # Frozen config at execution time
    config_snapshot: dict = Field(default_factory=dict, sa_column=Column(JSON, nullable=False, server_default="{}"))
    snapshot_version: int = Field(default=1)

    # Run parameters
    sample_size: int | None = Field(default=None)
    total_patients: int = Field(default=0)
    processed_patients: int = Field(default=0)
    failed_patients: int = Field(default=0)
    is_cancelled: bool = Field(default=False)

    # Results
    result_summary: dict | None = Field(default=None, sa_column=Column(JSON, nullable=True))
    progress: int = Field(default=0)

    # Metadata
    created_by: str = Field(default="")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    started_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True),
    )
    completed_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True),
    )


class PatientTask(SQLModel, table=True):
    """Per-patient work unit within a pipeline run.

    Workers claim tasks via SKIP LOCKED (PostgreSQL) or CAS update (SQLite).
    """

    __tablename__ = "patient_tasks"
    __table_args__ = (
        Index("ix_patient_tasks_run_status", "pipeline_run_id", "status"),
    )

    id: int | None = Field(default=None, primary_key=True)
    pipeline_run_id: str = Field(foreign_key="pipeline_runs.id", index=True)
    patient_id: str = Field(index=True)

    status: PatientTaskStatus = Field(default=PatientTaskStatus.QUEUED)

    # Search results
    notes_searched: int = Field(default=0)
    notes_matched: int = Field(default=0)

    # Classification result (patient-level)
    finding_label: str | None = Field(default=None, max_length=20)
    finding_reasoning: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    finding_evidence: dict | None = Field(default=None, sa_column=Column(JSON, nullable=True))
    predicted_score: float | None = Field(default=None)

    # Cost tracking
    token_usage: dict | None = Field(default=None, sa_column=Column(JSON, nullable=True))

    # Error info
    error_message: str | None = Field(default=None, sa_column=Column(Text, nullable=True))

    # Timestamps
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    started_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True),
    )
    completed_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True),
    )

    def transition_status(self, new_status: PatientTaskStatus) -> None:
        """Transition to a new status, validating the transition is allowed.

        Raises ValueError if the transition is not valid.
        """
        allowed = _PATIENT_TASK_TRANSITIONS.get(self.status, set())
        if new_status not in allowed:
            raise ValueError(
                f"Invalid transition: {self.status.value} → {new_status.value}. "
                f"Allowed: {', '.join(s.value for s in allowed) or 'none'}"
            )
        self.status = new_status


class Evidence(SQLModel, table=True):
    """A matched text span within a note, linking a PatientTask to specific evidence."""

    __tablename__ = "evidence"

    id: int | None = Field(default=None, primary_key=True)
    patient_task_id: int = Field(foreign_key="patient_tasks.id", index=True)
    note_id: str = Field(foreign_key="notes.id", index=True)

    # Matched text
    text: str = Field(sa_column=Column(Text, nullable=False))
    start_pos: int = Field(default=0)
    end_pos: int = Field(default=0)

    # Match metadata
    match_source: str = Field(max_length=20)  # "keyword", "regex", "negation"
    match_pattern: str = Field(default="", max_length=500)
