# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
  command: server --console-address ":9001" http://minio/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ROOTUSER
    MINIO_ROOT_PASSWORD: CHANGEME123
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5
services:
  web:
    build:
      context: .
      dockerfile: ./cedars/Dockerfile
    image: cedars
    restart: always
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    depends_on:
      - db
    networks:
      - cedars
  db:
    image: mongo:latest
    ports:
      - 27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - cedars_db:/data/db
    command: mongod --quiet --logpath /dev/null 
    networks:
      - cedars
  minio:
    <<: *minio-common
    hostname: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    networks:
      - cedars
  
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - minio
      - pines
    networks:
      - cedars
  pines:
    build:
      context: ./PINES
    deploy:
      mode: replicated
      replicas: 2
    restart: on-failure:5
    networks:
      - cedars
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - cedars
  worker:
    image: cedars
    command: python -m app.make_rq
    scale: 2
    networks:
      - cedars
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  cedars_db:
  redis_data:
networks:
  cedars:
    driver: bridge
