version: '3.8'
# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: docker.io/minio/minio
  command: server --console-address ":9001" http://minio/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ROOTUSER
    MINIO_ROOT_PASSWORD: CHANGEME123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
services:
  web:
    build: .
    ports:
      - 5001:5000
    volumes:
      - .:/app
    depends_on:
      - db
      - minio
  db:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      
  minio:
    <<: *minio-common
    hostname: minio
    volumes:
      - data2-1:/data1
      - data2-2:/data2
  
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2: