AWSTemplateFormatVersion: '2010-09-09'
Description: Fully self-contained CEDARS with AutoScaling for CPU BERT Model via SQS

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  PINESInstanceType:
    Type: String
    Default: t3.xlarge
    AllowedValues:
      - t3.xlarge
  
  WebServerInstanceType:
    Description: CEDARS CPU EC2 instance type
    Type: String
    Default: t3.xlarge
    AllowedValues:
      - t3.xlarge
      - t3.2xlarge
  
  MinioBucketTitle:
    Type: String
    Default: cedars-minio-bucket
    Description: Lowercase project identifier (used for S3 bucket names)
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: must contain only lowercase letters, numbers, and hyphens
  
  ModelS3Path:
    Type: String
    Default: s3://pines-models-storage/models/bert-tiny/
    Description: Path to BERT model stored on S3
    AllowedValues:
      - s3://pines-models-storage/models/bert-tiny/

Resources:
# -----------------------
# SQS Queue
# -----------------------
  InferenceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: bert-inference
      VisibilityTimeout: 900
      MessageRetentionPeriod: 86400

  ResponseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: bert-response
      VisibilityTimeout: 900
      MessageRetentionPeriod: 86400

# -----------------------
# Minio Storage Bucket
# -----------------------
  CedarsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${MinioBucketTitle}"
      VersioningConfiguration:
        Status: Enabled

# -----------------------
# Web Server Security Rules
# -----------------------
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group For CEDARS EC2 connections
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5001
          ToPort: 5001
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

# -----------------------
# Web Server IAM Role
# -----------------------
  SenderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SQSSenderPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt InferenceQueue.Arn

              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt ResponseQueue.Arn

        - PolicyName: MinioS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::${CedarsBucket}"
                  - !Sub "arn:aws:s3:::${CedarsBucket}/*"

  SenderInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SenderRole

# -----------------------
# Web Server EC2
# -----------------------
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      InstanceType: !Ref WebServerInstanceType
      IamInstanceProfile: !Ref SenderInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 64
            VolumeType: gp3
            DeleteOnTermination: true
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Update system
          dnf update -y

          # Install dnf plugin
          dnf -y install dnf-plugins-core
          # Add CentOS repository
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          # Adjust release server version in the path as it will not match with Amazon Linux 2023
          sed -i 's/$releasever/9/g' /etc/yum.repos.d/docker-ce.repo
          # Install as usual
          dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          # Enable the docker service
          systemctl enable --now docker

          # Install Docker, Docker Compose and Git
          dnf install -y git

          mkdir -p /home/ec2-user/CEDARS
          cd /home/ec2-user/

          # Get CEDARS
          git clone https://github.com/CEDARS-NLP/CEDARS.git --branch aws_template CEDARS
          cd /home/ec2-user/CEDARS

          # Get the PINES submodule
          git submodule init
          git submodule update

          # Add the .env files

          export DB_PASSWORD=$(tr -dc 'A-Za-z0-9_' </dev/urandom | head -c 24)
          export MINIO_PASSWORD=$(tr -dc 'A-Za-z0-9_' </dev/urandom | head -c 24)
          export PROJECT_ID=$(tr -dc 'a-z0-9' </dev/urandom | head -c 24)
          export SECRET_KEY=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24)

          cat > /home/ec2-user/CEDARS/.env << EOF
          DB_PORT=27017
          DB_HOST_PORT=27018
          DB_USER=admin
          DB_PWD=$DB_PASSWORD
          MINIO_HOST=minio
          MINIO_PORT=9000
          MINIO_ACCESS_KEY=rootuser
          MINIO_SECRET_KEY=$MINIO_PASSWORD
          MINIO_VERSION=RELEASE.2024-05-10T01-41-38Z
          S3_BUCKET_NAME=${CedarsBucket}
          AWS_REGION=${AWS::Region}
          MINIO_CONNECTION_TYPE=LOCAL_DOCKER
          ENV=prod
          REDIS_PORT=6379
          WORKER_SCALE=2
          GPU_SCALE=1
          PINES_WORKERS=1
          BERT_INFERENCE_TYPE=SQS_Inference
          INFERENCE_QUEUE_URL=${InferenceQueue}
          RESPONSE_QUEUE_URL=${ResponseQueue}
          EOF

          cat > /home/ec2-user/CEDARS/cedars/.env << EOF
          PROJECT_ID=$PROJECT_ID
          SECRET_KEY=$SECRET_KEY
          HOST=0.0.0.0
          DB_HOST=db
          DB_NAME=cedars
          DB_PORT=27017
          DB_HOST_PORT=27018
          DB_USER=admin
          DB_PWD=$DB_PASSWORD
          DB_PARAMS="authSource=admin"
          MINIO_HOST=minio
          MINIO_PORT=9000
          MINIO_ACCESS_KEY=rootuser
          MINIO_SECRET_KEY=$MINIO_PASSWORD
          S3_BUCKET_NAME=${CedarsBucket}
          AWS_REGION=${AWS::Region}
          MINIO_CONNECTION_TYPE=LOCAL_DOCKER
          ENV=dev
          PINES_API_URL=http://pines:8036
          REDIS_URL=redis
          REDIS_PORT=6379
          RQ_DASHBOARD_URL=/rq
          PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus-multiproc
          BERT_INFERENCE_TYPE=SQS_Inference
          INFERENCE_QUEUE_URL=${InferenceQueue}
          RESPONSE_QUEUE_URL=${ResponseQueue}
          EOF

          systemctl start docker
          systemctl enable docker

          echo "Starting docker build"
          docker compose --profile selfhosted --profile cpu build --no-cache
          echo "Finished docker build"
          docker compose --profile selfhosted --profile cpu up -d
          echo "Docker is now running"


# -----------------------
# S3 Bucket CleanUp
# -----------------------
  BucketCleanupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Cleanup
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:ListBucketVersions
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                Resource:
                  - !Sub "arn:aws:s3:::${CedarsBucket}"
                  - !Sub "arn:aws:s3:::${CedarsBucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  BucketCleanupFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.10
      Handler: index.handler
      Role: !GetAtt BucketCleanupRole.Arn
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import logging
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def handler(event, context):
              logger.info(f"Event: {event}")
              bucket_name = event["ResourceProperties"]["BucketName"]
              
              try:
                  if event["RequestType"] == "Delete":
                      s3 = boto3.resource("s3")
                      bucket = s3.Bucket(bucket_name)
                      
                      logger.info(f"Deleting all objects and versions from bucket: {bucket_name}")
                      
                      # Delete all object versions and delete markers
                      bucket.object_versions.all().delete()
                      
                      logger.info(f"Successfully emptied bucket: {bucket_name}")
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  logger.error(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {"Error": str(e)})

  
  EmptyBucketOnDelete:
    Type: Custom::EmptyS3Bucket
    DependsOn: CedarsBucket
    Properties:
      ServiceToken: !GetAtt BucketCleanupFunction.Arn
      BucketName: !Ref CedarsBucket

# -----------------------
# IAM Roles
# -----------------------
  BERTInferenceInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  BERTInferenceInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BERTInferenceInstanceRole
  


# -----------------------
# Launch Template
# -----------------------
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: !Ref PINESInstanceType
        ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
        IamInstanceProfile:
          Name: !Ref BERTInferenceInstanceProfile
        BlockDeviceMappings:
          - DeviceName: /dev/xvda   # Root volume (use /dev/sda1 for some AMIs)
            Ebs:
              VolumeSize: 64        # Size in GB
              VolumeType: gp3
              DeleteOnTermination: true
              Encrypted: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e

            # Update system
            dnf update -y

            # Install dnf plugin
            dnf -y install dnf-plugins-core
            # Add CentOS repository
            dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
            # Adjust release server version in the path as it will not match with Amazon Linux 2023
            sed -i 's/$releasever/9/g' /etc/yum.repos.d/docker-ce.repo
            # Install as usual
            dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            # Enable the docker service
            systemctl enable --now docker

            # Install Git
            dnf install -y git

            usermod -aG docker ec2-user

            # Clone repo
            cd /home/ec2-user
            git clone https://github.com/Kayan1920/PINES-ECS-DEPLOYMENT.git  --branch base_template app
            cd app

            cat > /home/ec2-user/app/.env << EOF
            MODEL_S3_PATH=${ModelS3Path}
            MAX_LENGTH=256
            AWS_REGION=${AWS::Region}
            QUEUE_URL=${InferenceQueue}
            EOF

            systemctl enable docker
            systemctl start docker

            # Build Docker image
            echo "Starting docker build"
            docker build -t bert-worker .
            echo "Finished docker build"
            docker run -d --restart unless-stopped --env-file .env bert-worker
            echo "Docker is now running"

# -----------------------
# Auto Scaling Group
# -----------------------
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: 0
      MaxSize: 1
      DesiredCapacity: 0
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber

# -----------------------
# Scale Policies
# -----------------------
  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      AdjustmentType: ChangeInCapacity
      ScalingAdjustment: 1
      Cooldown: 60

  QueueDepthHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt InferenceQueue.QueueName
      AlarmActions:
        - !Ref ScaleUpPolicy

  ScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      AdjustmentType: ChangeInCapacity
      ScalingAdjustment: -1
      Cooldown: 1800 # 30 minute cooldown

  QueueDepthLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 30
      Threshold: 0
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt InferenceQueue.QueueName
      AlarmActions:
        - !Ref ScaleDownPolicy

Outputs:
  InferenceQueueURL:
    Value: !Ref InferenceQueue
  
  ResponseQueueURL:
    Value: !Ref ResponseQueue

  WebsiteURL:
    Value: !Join
      - ''
      - - http://
        - !GetAtt WebServer.PublicDnsName
    Description: Website URL