"""add sentences search_queries nlp_jobs tables

Revision ID: 24f6465554d1
Revises: cb823cce26fd
Create Date: 2026-03-03 16:51:12.388744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24f6465554d1'
down_revision: Union[str, Sequence[str], None] = 'cb823cce26fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nlp_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='nlpjobstatus'), nullable=False),
    sa.Column('total_notes', sa.Integer(), nullable=False),
    sa.Column('processed_notes', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nlp_jobs_project_id'), 'nlp_jobs', ['project_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('nlp_apply', sa.Boolean(), nullable=False),
    sa.Column('hide_duplicates', sa.Boolean(), nullable=False),
    sa.Column('skip_after_event', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_project_id'), 'search_queries', ['project_id'], unique=False)
    op.create_table('sentences',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sentence_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_pos', sa.Integer(), nullable=False),
    sa.Column('end_pos', sa.Integer(), nullable=False),
    sa.Column('is_negated', sa.Boolean(), nullable=False),
    sa.Column('is_target', sa.Boolean(), nullable=False),
    sa.Column('matched_tokens', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'sentence_number', name='uq_sentence_note_pos')
    )
    op.create_index(op.f('ix_sentences_note_id'), 'sentences', ['note_id'], unique=False)
    op.create_index(op.f('ix_sentences_project_id'), 'sentences', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentences_project_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_note_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_search_queries_project_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_nlp_jobs_project_id'), table_name='nlp_jobs')
    op.drop_table('nlp_jobs')
    sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='nlpjobstatus').drop(op.get_bind())
    # ### end Alembic commands ###
