"""add background_jobs table

Revision ID: 97ab483a9f89
Revises: 021e1fe9ce58
Create Date: 2026-03-03 21:47:45.798119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97ab483a9f89'
down_revision: Union[str, Sequence[str], None] = '021e1fe9ce58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_type', sa.Enum('NLP', 'PREDICTION', 'EXPORT', name='jobtype'), nullable=False),
    sa.Column('arq_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_arq_job_id'), 'background_jobs', ['arq_job_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_project_id'), 'background_jobs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_background_jobs_project_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_arq_job_id'), table_name='background_jobs')
    op.drop_table('background_jobs')
    sa.Enum('NLP', 'PREDICTION', 'EXPORT', name='jobtype').drop(op.get_bind())
    sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus').drop(op.get_bind())
    # ### end Alembic commands ###
