"""add pipeline tables

Revision ID: b4de01f3eae0
Revises: c3a1e7f82d9b
Create Date: 2026-03-05 14:04:20.650086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4de01f3eae0'
down_revision: Union[str, Sequence[str], None] = 'c3a1e7f82d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_project_patient_review'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_project_review_created'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_sentence_project'), table_name='annotations')
    op.drop_index(op.f('ix_notes_patient_notedate'), table_name='notes')
    op.drop_index(op.f('ix_notes_project_patient_deleted'), table_name='notes')
    op.drop_index(op.f('ix_sentences_project_target_created'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_project_target_negated'), table_name='sentences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sentences_project_target_negated'), 'sentences', ['project_id', 'is_target', 'is_negated'], unique=False)
    op.create_index(op.f('ix_sentences_project_target_created'), 'sentences', ['project_id', 'is_target', 'created_at'], unique=False)
    op.create_index(op.f('ix_notes_project_patient_deleted'), 'notes', ['project_id', 'patient_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_notes_patient_notedate'), 'notes', ['patient_id', 'note_date'], unique=False)
    op.create_index(op.f('ix_annotations_sentence_project'), 'annotations', ['sentence_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_annotations_project_review_created'), 'annotations', ['project_id', 'review_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_annotations_project_patient_review'), 'annotations', ['project_id', 'patient_id', 'review_status'], unique=False)
    # ### end Alembic commands ###
