"""add text_id column to notes table

Revision ID: cb823cce26fd
Revises: 9b5271d49753
Create Date: 2026-03-03 16:17:23.848101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb823cce26fd'
down_revision: Union[str, Sequence[str], None] = '9b5271d49753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('text_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_notes_text_id'), 'notes', ['text_id'], unique=False)
    op.create_unique_constraint('uq_note_text_id', 'notes', ['project_id', 'text_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_note_text_id', 'notes', type_='unique')
    op.drop_index(op.f('ix_notes_text_id'), table_name='notes')
    op.drop_column('notes', 'text_id')
    # ### end Alembic commands ###
