"""add audit_log table

Revision ID: cd56927de56d
Revises: 97ab483a9f89
Create Date: 2026-03-04 06:52:02.482313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd56927de56d'
down_revision: Union[str, Sequence[str], None] = '97ab483a9f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.Enum('ANNOTATION_REVIEWED', 'ANNOTATION_SKIPPED', 'EVENT_DATE_SET', 'EVENT_DATE_DELETED', 'PATIENT_LOCKED', 'PATIENT_UNLOCKED', 'PATIENT_REOPENED', 'PREDICTION_RAN', 'AUTO_ADJUDICATED', 'DATA_INGESTED', 'DATA_PURGED', 'DATA_RESYNCED', name='auditaction'), nullable=False),
    sa.Column('detail', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_project_id'), 'audit_log', ['project_id'], unique=False)
    op.create_index('ix_audit_project_created', 'audit_log', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_audit_project_patient', 'audit_log', ['project_id', 'patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_project_patient', table_name='audit_log')
    op.drop_index('ix_audit_project_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_project_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
