"""add annotations table

Revision ID: e0bd984ffdcf
Revises: 24f6465554d1
Create Date: 2026-03-03 17:02:47.196727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0bd984ffdcf'
down_revision: Union[str, Sequence[str], None] = '24f6465554d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sentence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sentence_text', sa.Text(), nullable=False),
    sa.Column('matched_tokens', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_negated', sa.Boolean(), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('predicted_label', sa.Integer(), nullable=True),
    sa.Column('predictor_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning', sa.Text(), server_default='', nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'REVIEWED', 'SKIPPED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_note_id'), 'annotations', ['note_id'], unique=False)
    op.create_index(op.f('ix_annotations_patient_id'), 'annotations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_annotations_project_id'), 'annotations', ['project_id'], unique=False)
    op.create_index(op.f('ix_annotations_sentence_id'), 'annotations', ['sentence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_sentence_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_project_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_patient_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_note_id'), table_name='annotations')
    op.drop_table('annotations')
    sa.Enum('UNREVIEWED', 'REVIEWED', 'SKIPPED', name='reviewstatus').drop(op.get_bind())
    # ### end Alembic commands ###
